routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace' => 'Website'], function () {
    Route::post('login', 'CustomerController@postLogin')->name('customer.login');
    Route::post('logout', 'CustomerController@logout')->name('customer.logout');
    Route::post('register', 'CustomerController@postRegister')->name('customer.register');

    Route::group(['middleware' => 'CheckLoginCustomer'], function () {
        Route::post('trang-ca-nhan', 'CustomerController@changeProfile')->name('customer.change_profile');
        Route::get('don-hang', 'CustomerController@getListOrder')->name('customer.history.order');
        Route::get('chi-tiet-don-hang', 'CustomerController@getOrderDetail')->name('customer.order_detail');
        Route::post('doi-mat-khau', 'CustomerController@changePassword')->name('customer.change_password');
    });

    Route::post('quen-mat-khau', 'CustomerController@sendRequestForgotPassword')->name('customer.forgot_password');
    Route::get('token/{token}', 'CustomerController@checkToken')->name('customer.check_token');
    Route::post('dat-mat-khau', 'CustomerController@setPassword')->name('customer.set_password');

    Route::resource('cart', 'CartController')->except('edit', 'show', 'create');
    Route::get('cart/user-info', 'CartController@getUser')->name('cart.user_info');
    Route::get('cart/districts', 'CartController@getDistrict')->name('cart.districts');
    Route::get('cart/wards', 'CartController@getWard')->name('cart.wards');
    Route::post('cart/confirm', 'CartController@confirmOrder')->name('cart.confirm')->middleware('CheckLoginCustomer');
    Route::post('cart/confirm-vnpay', 'CartController@confirmOrderVnpay')->name('cart.confirm_vnpay');
    Route::post('cart/delete-all', 'CartController@deleteAllCart')->name('cart.delete_all_cart');
    Route::get('VnPayReturn', 'CartController@vnpayreturn')->name('vnpay');

    Route::get('/', 'PageController@index');
    Route::get('tim-kiem', 'PageController@searchProduct')->name('search_product');
    Route::post('binh-luan', 'PageController@postComment')->name('product.comment')->middleware('CheckLoginCustomer');
    Route::get('tin-tuc', 'PageController@getListNew')->name('list_new');
    Route::get('tin-tuc/{slug}', 'PageController@getNewDetail')->name('new_detail');
    Route::get('khuyen-mai/{slug}', 'PageController@getPromotionDetail')->name('promotion_detail');
    Route::get('chinh-sach', 'PageController@getPolicy')->name('policy_detail');

});
Route::get('test', 'Admin\UserController@test');
Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::group(['middleware' => 'CheckAdminLogout'], function () {
        Route::get('login', 'AuthController@getLogin')->name('admin.get_login');
        Route::post('login', 'AuthController@postLogin')->name('admin.post_login');
        Route::post('forgot-password', 'AuthController@sendRequestForgotPassword')->name('admin.forgot_password');
        Route::get('token/{token}', 'AuthController@checkToken')->name('admin.check_token');
        Route::post('token', 'AuthController@resetPassword')->name('admin.reset_password');
    });
    Route::group(['middleware' => 'CheckAdminLogin'], function () {
        Route::post('logout', 'AuthController@postLogout')->name('admin.logout');
        Route::get('profile', 'AuthController@getProfile')->name('admin.profile');
        Route::post('profile', 'AuthController@postProfile')->name('admin.change_profile');
        Route::post('change-password', 'AuthController@changePassword')->name('admin.change_password');
    });
    Route::group(['middleware' => 'Admin'], function () {
        Route::get('/', 'HomeController@index')->name('admin.home');
        Route::get('statistics', 'OrderController@getStatistics')->name('admin.statistics');
        Route::group(['prefix' => 'products'], function () {
            Route::get('/', 'ProductController@index')->name('admin.products');
            Route::get('/add', 'ProductController@createProduct')->name('admin.products.get_add_product');
            Route::post('/add', 'ProductController@storeProduct')->name('admin.products.post_add_product');
            Route::get('{product}/edit', 'ProductController@editProduct')->name('admin.products.get_edit_product');
            Route::post('{product}/edit', 'ProductController@updateProduct')->name('admin.products.post_edit_product');
            Route::delete('{product}/delete', 'ProductController@deleteProduct')->name('admin.products.delete');
            Route::delete('image/{image}/delete', 'ProductController@deleteImage')->name('admin.products.delete_image');
            Route::delete('option/{option}/delete', 'ProductController@deleteOption')->name('admin.products.delete_option');
            Route::post('{id}/restore', 'ProductController@restoreProduct')->name('admin.products.restore');
        });
        Route::group(['prefix' => 'brands'], function () {
            Route::get('/', 'BrandController@index')->name('admin.brands');
            Route::get('add', 'BrandController@createBrand')->name('admin.brands.get_add_brand');
            Route::post('add', 'BrandController@storeBrand')->name('admin.brands.post_add_brand');
            Route::get('{brand}/edit', 'BrandController@editBrand')->name('admin.brands.get_edit_brand');
            Route::post('{brand}/edit', 'BrandController@updateBrand')->name('admin.brands.post_edit_brand');
            Route::delete('{brand}/delete', 'BrandController@deleteBrand')->name('admin.brands.delete');
            Route::post('{id}/restore', 'BrandController@restoreBrand')->name('admin.brands.restore');
        });
        Route::group(['prefix' => 'categories'], function () {
            Route::get('/', 'CategoryController@index')->name('admin.categories');
//            Route::get('/add', 'CategoryController@create');
//            Route::post('/add', 'CategoryController@store');
//            Route::get('{category}/edit', 'CategoryController@Edit')->name('admin.category.get-edit-category');
            Route::post('{category}/edit', 'CategoryController@updateCategory')->name('admin.categories.post_edit_category');
//            Route::get('{category}/delete', 'CategoryController@destroy');
        });
        Route::group(['prefix' => 'customers'], function () {
            Route::get('/', 'CustomerController@index')->name('admin.customers');
            Route::get('{id}/profile', 'CustomerController@getProfile')->name('admin.customers.profile');
        });
        Route::group(['prefix' => 'orders'], function () {
            Route::get('/', 'OrderController@index')->name('admin.orders');
            Route::get('{order}/detail', 'OrderController@getDetail')->name('admin.orders.detail');
            Route::post('{order}/update', 'OrderController@updateOrder')->name('admin.orders.update');

        });
        Route::group(['prefix' => 'news'], function () {
            Route::get('/', 'NewController@index')->name('admin.news');
            Route::get('/add', 'NewController@createNew')->name('admin.news.get_add_new');
            Route::post('/add', 'NewController@storeNew')->name('admin.news.post_add_new');
            Route::get('{new}/edit', 'NewController@editNew')->name('admin.news.get_edit_new');
            Route::post('{new}/edit', 'NewController@updateNew')->name('admin.news.post_edit_new');
            Route::delete('{new}/delete', 'NewController@deleteNew')->name('admin.news.delete');
            Route::post('{new}/restore', 'NewController@restoreNew')->name('admin.news.restore');
        });
        Route::group(['prefix' => 'banners'], function () {
            Route::get('/', 'BannerController@index')->name('admin.banners');
            Route::get('/add', 'BannerController@createBanner')->name('admin.banners.get_add_banner');
            Route::post('/add', 'BannerController@storeBanner')->name('admin.banners.post_add_banner');
            Route::get('{banner}/edit', 'BannerController@editBanner')->name('admin.banners.get_edit_banner');
            Route::post('{banner}/edit', 'BannerController@updateBanner')->name('admin.banners.post_edit_banner');
            Route::delete('{banner}/delete', 'BannerController@deleteBanner')->name('admin.banners.delete');
            Route::post('{banner}/restore', 'BannerController@restoreBaner')->name('admin.banners.restore');
        });
    });
    Route::group(['prefix' => 'users', 'middleware' => 'SuperAdmin'], function () {
        Route::get('/', 'UserController@index')->name('admin.users');
        Route::get('/add', 'UserController@createUser')->name('admin.users.get_add_user');
        Route::post('/add', 'UserController@storeUser')->name('admin.users.post_add_user');
        Route::delete('{user}/disable', 'UserController@disableUser')->name('admin.users.disable');
        Route::post('{user}/restore', 'UserController@restoreUser')->name('admin.users.restore');
        Route::post('{user}/reset', 'UserController@resetUser')->name('admin.users.reset');
    });
});

Route::get('{category}', 'Website\PageController@getListProduct')->name('category');
Route::get('{c_slug}/{p_slug}', 'Website\PageController@getProductDetail')->name('product.detail');

app/Http/Controllers/Website/CustomerController.php
<?php

namespace App\Http\Controllers\website;

use App\Http\Controllers\Controller;
use App\Http\Requests\ChangePassword;
use App\Http\Requests\CustomerChangeProfile;
use App\Http\Requests\CustomerResetPassword;
use App\Http\Requests\CustomerSendRequestForgotPassword;
use App\Http\Requests\LoginRequest;
use App\Http\Requests\Register;
use App\Mail\CustomerForgotPassword;
use App\Mail\CustomerRegisterSuccess;
use App\Models\Customer;
use App\Models\Order;
use App\Models\OrderDetail;
use Carbon\Carbon;
use Illuminate\Support\Facades\Mail;
use Validate;
use Illuminate\Http\Request;
use Session;
use Auth;
use Cart;
use DB;

class CustomerController extends Controller
{
    protected $customer, $order, $orderdetail;

    /**
     * CustomerController constructor.
     * @param Customer $customer
     */
    public function __construct(Customer $customer, Order $order, OrderDetail $orderDetail)
    {
        $this->customer = $customer;
        $this->orderdetail = $orderDetail;
        $this->order = $order;
    }

    /**
     * Login
     *
     * @param LoginRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function postLogin(LoginRequest $request)
    {
        $arr = [
            'email' => $request->email,
            'password' => $request->password,
        ];
        $remember = false;
        if ($request->has('remember')) {
            $remember = true;
        }
        if (Auth::guard('customers')->attempt($arr, $remember)) {
            $name = Auth::guard('customers')->user()->name;
            return response()->json($name, 200);
        }
        return response()->json('error', 500);
    }

    /**
     * Logout
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function Logout(Request $request)
    {
        Session::remove(Auth::guard('customers')->getName());
        return response()->json('success', 200);
    }

    /**
     * Register
     *
     * @param Register $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function postRegister(Register $request)
    {
        $this->customer->fill($request->only('name', 'email', 'password', 'phone', 'address'));
        $this->customer->password = bcrypt($request->password);
        $this->customer->save();
        Mail::to($this->customer->email)->send(new CustomerRegisterSuccess($this->customer));
        return response()->json(['success' => 'Data is successfully added']);
    }

    /**
     * Update profile
     *
     * @param CustomerChangeProfile $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function changeProfile(CustomerChangeProfile $request)
    {
        if (Auth::guard('customers')->check()) {
            $customer = $this->customer->where('email', Auth::guard('customers')->user()->email)->first();
            $customer->fill($request->only('name', 'phone', 'address'));
            $customer->save();
            return response()->json($customer, 200);
        }
        return response()->json(false, 500);
    }

    /**
     * Change password
     *
     * @param ChangePassword $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function changePassword(ChangePassword $request)
    {
        $user = Auth::guard('customers')->user();
        $user->password = bcrypt($request->password);
        $user->save();
        Auth::guard('customers')->logout();
        return response()->json(true, 204);
    }

    /**
     * Get list order
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function getListOrder()
    {
        $user = $this->customer->find(Auth::guard('customers')->user()->id);
        $data['orders'] = $user->order()->orderBy('created_at', 'DESC')->get();
        $query = DB::table('orders')
            ->select('orders.id', DB::raw("SUM(B.price * B.quantity) as money"))
            ->join('order_detail as B', 'B.order_id', '=', 'orders.id')
            ->where('orders.customer_id', $user->id)
            ->groupBy('orders.id');
        $data['money'] = $query->get();
        return view('website.cart.history_order', $data);
    }

    public function getOrderDetail(Request $request)
    {
        $order = $this->order->find($request->id);
        $list = [];
        $products = $order->product()->with('product_type:product_id,stock_price')->get();
        $detail = $order->order_detail()->get();
        foreach ($products as $i => $product) {
            $list[$i] = [
                'image' => $product->image,
                'name' => $product->name,
                'product_type' => $detail[$i]->product_type,
                's_price' => $product->product_type[$i]->stock_price,
                'p_price' => $detail[$i]->price,
                'quantity' => $detail[$i]->quantity,
            ];
        }
        $data['order'] = $order;
        $data['list'] = $list;
        $data['customer'] = $this->customer->find($order->customer_id);
        $data['address'] = DB::table('wards AS W')
            ->join('districts AS D', 'D.id', '=', 'W.district_id')
            ->join('provinces AS P', 'P.id', '=', 'D.province_id')
            ->select('W.name AS w_name', 'D.name AS d_name', 'P.name AS p_name')
            ->where('W.id', '=', $order->ward_id)
            ->get();
        return response()->json($data, 200);
    }

    /**
     * Send Request Forgot Password
     *
     * @param CustomerSendRequestForgotPassword $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function sendRequestForgotPassword(CustomerSendRequestForgotPassword $request)
    {
        if (Auth::guard('customers')->check()) {
            Auth::guard('customers')->logout();
        }
        $email = $request->email;
        $customer = $this->customer->where('email', $email)->first();
        if ($customer) {
            $customer->token = md5(time() . str_random(50));
            $customer->token_expire = date('Y-m-d H:i:s', time());
            $customer->save();
            Mail::to($customer->email)->send(new CustomerForgotPassword($customer));
            return response()->json('success', 204);
        }
        return response()->json('error', 400);
    }


    /**
     * Check Token Forgot Password
     *
     * @param null $token
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|\Illuminate\View\View
     */
    public function checkToken($token = null)
    {
        if (Auth::guard('customers')->check()) {
            Auth::guard('customers')->logout();
        }
        $customer = $this->customer->where('token', $token)->first();
        if ($customer) {
            $time = Carbon::now()->subHours(24);
            if ($customer->token_expire >= $time) {
                return view('website.auth.forgot_password', ['customer' => $customer]);
            }
            return view('website.auth.error_token');
        }
        return view('website.auth.error_token');
    }

    public function setPassword(CustomerResetPassword $request)
    {
        if (Auth::guard('customers')->check()) {
            Auth::guard('customers')->logout();
        }
        $customer = $this->customer->where('token', $request->token)->first();
        $customer->token = null;
        $customer->token_expire = null;
        $customer->password = bcrypt($request->password);
        $customer->save();
        return response()->json('success', 204);
    }
}

app/Http/Controllers/Website/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/website/product/filter.blade.php
<!-- Left Content -->
<style>
    @media (max-width: 960px) {
        #left-content {
            display: none;
        }
    }
</style>
<div id="left-content" class="col-lg-2 mt-lg-0 mt-4 p-lg-0">
    <div class="side-bar p-sm-4 p-3">
        <form action="">
            <!-- price -->
            <div class="range border-bottom py-2">
                <h3 class="agileits-sear-head mb-3">Theo giá</h3>
                <div class="w3l-range">
                    <div class="custom-control custom-radio">
                        <input @if (isset($gia) && $gia == 'duoi-1-trieu') checked @endif type="radio" id="price1" name="gia"
                               value="duoi-1-trieu" class="custom-control-input">
                        <label class="custom-control-label" for="price1">Dưới 1 triệu</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input @if (isset($gia) && $gia == 'tu-1-3-trieu') checked @endif type="radio" id="price2" name="gia"
                               value="tu-1-3-trieu" class="custom-control-input">
                        <label class="custom-control-label" for="price2">Từ 1-3 triệu</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input @if (isset($gia) && $gia == 'tu-3-7-trieu') checked @endif type="radio" id="price3" name="gia"
                               value="tu-3-7-trieu" class="custom-control-input">
                        <label class="custom-control-label" for="price3">Từ 3-7 triệu</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input @if (isset($gia) && $gia == 'tu-7-12-trieu') checked @endif type="radio" id="price4" name="gia"
                               value="tu-7-12-trieu" class="custom-control-input">
                        <label class="custom-control-label" for="price4">Từ 7-12 triệu</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input @if (isset($gia) && $gia == 'tu-12-17-trieu') checked @endif type="radio" id="price5"
                               name="gia" value="tu-12-17-trieu" class="custom-control-input">
                        <label class="custom-control-label" for="price5">Từ 12-17 triệu</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input @if (isset($gia) && $gia == 'tren-17-trieu') checked @endif type="radio" id="price6" name="gia"
                               value="tren-17-trieu" class="custom-control-input">
                        <label class="custom-control-label" for="price6">Trên 17 triệu</label>
                    </div>
                </div>
            </div>
            <!-- //price -->
            <!-- brand -->
            <div class="left-side border-bottom py-2">
                <h3 style="margin-top: 17px" class="agileits-sear-head mb-3">Theo hãng</h3>
                @foreach($brands as $brand)
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" value="{{ $brand->id }}" class="custom-control-input"
                               id="{{ $brand->slug }}" name="hang[]"
                               @if(isset($hang) && in_array($brand->id, $hang)) checked @endif>
                        <label class="custom-control-label" for="{{ $brand->slug }}">{{ $brand->name }}</label>
                    </div>
                @endforeach
            </div>
            <!-- //brand -->
            <!-- order by -->
            <div class="left-side border-bottom py-2">
                <h3 style="margin-top: 17px" class="agileits-sear-head mb-3">Sắp xếp</h3>
                <div class="custom-control custom-radio">
                    <input @if (isset($sap_xep) && $sap_xep == 'gia-tang-dan') checked @endif value="gia-tang-dan" type="radio" id="priceup" name="sap_xep" class="custom-control-input">
                    <label class="custom-control-label" for="priceup">Giá tăng dần</label>
                </div>
                <div class="custom-control custom-radio">
                    <input @if (isset($sap_xep) && $sap_xep == 'gia-giam-dan') checked @endif value="gia-giam-dan" type="radio" id="pricedown" name="sap_xep" class="custom-control-input">
                    <label class="custom-control-label" for="pricedown">Giá giảm dần</label>
                </div>
                <div class="custom-control custom-radio">
                    <input @if (isset($sap_xep) && $sap_xep == 'moi-nhat') checked @endif value="moi-nhat" type="radio" id="newest" name="sap_xep" class="custom-control-input">
                    <label class="custom-control-label" for="newest">Mới nhất</label>
                </div>
            </div>
            <!-- //order by -->
            <input style="margin-top: 17px" type="submit" class="btn col-md-12 btn-info" value="OK">
        </form>
    </div>
</div>
<!-- /Left Content -->

resources/views/website/product/list_products.blade.php
@extends('website.layout.index')
@section('title', $category->name)
@section('container')
    <!-- top Products -->
    <div class="ads-grid py-sm-5 py-6">
        <div class="container py-xl-4 py-lg-2">
            <div class="row">
                <!-- Left Content -->
            @include('website.product.filter')
            <!-- /Left Content -->

                <!-- product right -->
                <div class="agileinfo-ads-display col-lg-10">
                    <div class="wrapper">
                        <!-- first section -->
                        <div class="product-sec1 px-sm-4 px-3 py-sm-5  py-3 mb-4">
                            <h3 class="heading-tittle text-center font-italic">{{ $category->name }}</h3>
                            <div class="row">
                                @php ([$sub_price = 0, $stock_price = 0, $promotion_price = 0, $star = 5, $comments = 0])
                                @foreach ($products as $product)
                                    @php ([
                                            $sub_price = $product->product_type[0]->stock_price - $product->product_type[0]->promotion_price,
                                            $stock_price = $product->product_type[0]->stock_price,
                                            $promotion_price = $product->product_type[0]->promotion_price,
                                            $star = isset($product->product_review[0]) ? round($product->product_review[0]->ave_star) : 5,
                                            $comments = isset($product->product_review[0]) ? $product->product_review[0]->comments . ' ' : '0 ',
                                    ])
                                    <div class="col-md-3 product-men">
                                        <div class="men-pro-item simpleCart_shelfItem">
                                            <div class="men-thumb-item text-center">
                                                <img height="195px"
                                                     src="{{ asset('storage/app/products/'. $product->image) }}" alt="">
                                                <div class="men-cart-pro">
                                                    <div class="inner-men-cart-pro">
                                                        <a href="{{ route('product.detail', [$category->slug, $product->slug]) }}"
                                                           class="link-product-add-cart">Chi tiết</a>
                                                    </div>
                                                </div>
                                                @if ($sub_price >= 10000)
                                                    <span class="product-new-top">
                                                    <del>Giảm: {{ number_format($sub_price) }}<sup>đ</sup></del>
                                                </span>
                                                @endif
                                            </div>
                                            <div class="item-info-product text-center border-top mt-4">
                                                <h4>
                                                    <a href="{{ route('product.detail', [$category->slug, $product->image]) }}">{{ $product->name }}</a>
                                                </h4>
                                                <div class="info-product-price my-2">
                                                    <span
                                                        class="item_price">{{ number_format($promotion_price) }}<sup>đ</sup></span>
                                                    @if ($sub_price >= 10000)
                                                        <del>{{ number_format($stock_price) }}<sup>đ</sup></del>
                                                    @endif
                                                </div>
                                                <div class="clearfix"></div>
                                                <div class="product-rating">
                                                    <div class="stars starrr"
                                                         data-rating="{{ $star }}">
                                                    </div>
                                                    <span>{{ $comments }}đánh giá</span>
                                                </div>
                                                <div
                                                    class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                                                    <button data-url="{{ route('cart.store') }}"
                                                            data-id="{{ $product->id }}"
                                                            data-type_id="{{ $product->product_type[0]->id }}"
                                                            class="btn btn-info btn-add-cart">Đặt mua
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <!-- //first section -->
                    </div>
                    <div class="pagination">
                        {!! $products->links() !!}
                    </div>
                </div>
                <!-- /product right -->
            </div>
        </div>

    </div>
    <!-- //top products -->
@stop